source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TankerHQ/PodSpecs.git'

target 'notepad' do
  use_frameworks!
  pod 'PromiseKit', '~> 1.7'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'Tanker', '2.0.0-alpha23'
end
